sudo: false
language: ruby
before_install: gem install bundler -v 1.10.6
env:
  - RAILS_VERSION="~> 3.2.22"
  - RAILS_VERSION="~> 4.0.13"
  - RAILS_VERSION="~> 4.1.16"
  - RAILS_VERSION="~> 4.2.7"
  - RAILS_VERSION="~> 5.0.1"
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - 2.0.0-p648
matrix:
  exclude:
  - rvm: 2.4.0
    env: RAILS_VERSION="~> 4.1.16"
  - rvm: 2.4.0
    env: RAILS_VERSION="~> 4.0.13"
  - rvm: 2.4.0
    env: RAILS_VERSION="~> 3.2.22"

